version: '3.3'
services:
    postgres:
        image: postgres
        ports:
            - "5463:5432"
        environment:
            POSTGRES_DB: metabase
            POSTGRES_USER: metabase
            POSTGRES_PASSWORD: metabase
    metabase:
        ports:
            - '3000:3000'
        environment:
            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=metabase
            - MB_DB_PASS=metabase
            - MB_DB_HOST=postgres
        container_name: metabase
        image: metabase/metabase