version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-database
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=Root@123!
      - ORACLE_SID=XE
      - ORACLE_DATABASE=ORCL

    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle_data: