version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      container_name: keycloak-postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        VIRTUAL_HOST: keycloak.solusione.id
        LETSENCRYPT_HOST: keycloak.solusione.id
        LETSENCRYPT_EMAIL: admin@solusione.id
        VIRTUAL_PORT: "8080"
        HTTPS_METHOD: redirect
        PROXY_ADDRESS_FORWARDING: "true" # <==== very important if you use reverse proxy
      volumes:
        - /opt/keycloak/data/import/realm.json
        
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        # JDBC_PARAMS: "ssl=true"
      ports:
        - 9090:8080
      depends_on:
        - postgres

networks:
  default:
    name: localhost
    external: true