version: '3'
services:
  odoo:
    image: odoo
    container_name: oddo
    environment:
      HOST: postgres
      USER: postgres
      DATABSE: oddo
      PASSWORD: root
    ports:
      - "8069:8069"

networks:
  default:
    name: localhost
    external: true