version: '3.3'
services:
  wordpress:
    container_name: 'local-wordpress'
    image: 'wordpress:latest'
    ports:
      - '8333:80'
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Root@123!
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"

networks:
  default:
    name: localhost
    external: true
