version: '3.9'

services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 3333:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=spring_db

networks:
  default:
    name: localhost
    external: true