version: '3.9'

services:
   postgres:
    image: postgres
    container_name: postgres
    command: -c 'max_connections=500'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data

networks:
  default:
    name: localhost
    external: true

volumes:
    pgadmin_volume: