version: '3.5'
services:
  postgresdb:
    container_name: postgres_solusione
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devops@
      PGDATA: /data/postgres
    volumes:
       - ../../databases/postgresdb:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@solusione.id
      PGADMIN_DEFAULT_PASSWORD: devops@
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    volumes:
        - pgadmin_volume:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgresdb

networks:
  postgres:
    driver: bridge

volumes:
    pgadmin_volume: