version: '3.8'

services:
  prometheus-pushgateway:
    image: prom/pushgateway
    restart: always
    # command: 
    ports:
      - 9091:9091
networks:
  default:
    external:
      name: localhost