version: '3'

services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - '/var/lib/bitnami'
      
networks:
  default:
    name: localhost
    external: true