version: '3'

services:
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "16379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      #- REDIS_PASSWORD=devops@solusione
    volumes:
      - '/path/to/redis-persistence:/bitnami'
      
networks:
  default:
    name: tms_microservice
    external: true